export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE'

export const CREATE_NEW_ARTICLE = 'CREATE_NEW_ARTICLE'
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE'

export const POST_ARTICLE_REQUEST = 'POST_ARTICLE_REQUEST'
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS'
export const POST_ARTICLE_FAILURE = 'POST_ARTICLE_FAILURE'

export const PUT_ARTICLE_REQUEST = 'PUT_ARTICLE_REQUEST'
export const PUT_ARTICLE_SUCCESS = 'PUT_ARTICLE_SUCCESS'
export const PUT_ARTICLE_FAILURE = 'PUT_ARTICLE_FAILURE'

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE'

export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED'
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED'
